# Generated by Django 5.0.1 on 2024-01-31 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
